### ISSUE TITLE
GUI failure in Windows + Spyder

### ISSUE THREAD

**Issue by loganbeal** [BYU-PRISM/GEKKO#35]
I get this error trying to launch the GUI from spyder in windows:

```
Starting Flask Thread on port 8050
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\SCD\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\SCD\Anaconda3\lib\site-packages\gekko\gk_gui.py", line 395, in run
    app.run(debug=False, port=self.port, threaded=True)
  File "C:\Users\SCD\Anaconda3\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "C:\Users\SCD\Anaconda3\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)
  File "C:\Users\SCD\Anaconda3\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
io.UnsupportedOperation: not writable
```

The same script works from the console and in Linux.

**Comment by abe-mart** [comment]
I actually ran into this same problem yesterday with spyder on mac.  It seems to be directly tied to this [plotly issue](https://github.com/plotly/dash/issues/257).  From the other page, it looks like Ipykernel 4.9 (not released yet) will fix the bug, or use this temporary work-around:

_You need to edit the echo function definition at ../site-packages/click/utils.py the default value for the file parameter must be sys.stdout instead of None.
Do the same for the secho function definition at ../site-packages/click/termui.py_

**Comment by abe-mart** [comment]
This issue seems to be resolved with the latest version of Spyder.  Closing.
